// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgHfHwtx85lQPyJmcsRbcuhw-XlsbOK7Q',
    appId: '1:601023447107:web:7dc72311c5b3f7ecb114f6',
    messagingSenderId: '601023447107',
    projectId: 'agriplant-1904047',
    authDomain: 'agriplant-1904047.firebaseapp.com',
    storageBucket: 'agriplant-1904047.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzofJeHSjTVtQDnUnxd98l9O4sO3xESgQ',
    appId: '1:601023447107:android:a539971a438ed824b114f6',
    messagingSenderId: '601023447107',
    projectId: 'agriplant-1904047',
    storageBucket: 'agriplant-1904047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79KuudB7q-jYmhvlHZrgzAvTT-0prDp8',
    appId: '1:601023447107:ios:7b27eeff0d984998b114f6',
    messagingSenderId: '601023447107',
    projectId: 'agriplant-1904047',
    storageBucket: 'agriplant-1904047.appspot.com',
    iosClientId: '601023447107-nt4n4i4ouao1u8m3ju3is7g42j0ld43r.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriplant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC79KuudB7q-jYmhvlHZrgzAvTT-0prDp8',
    appId: '1:601023447107:ios:8c1e6ff6644632a1b114f6',
    messagingSenderId: '601023447107',
    projectId: 'agriplant-1904047',
    storageBucket: 'agriplant-1904047.appspot.com',
    iosClientId: '601023447107-grr5h3f9ijgml3grdfi2c8gct84jjuc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriplant.RunnerTests',
  );
}
